[workspace]
git_only = true
publish = false
semver_check = false
dependencies_update = false
git_release_enable = true
git_tag_enable = true
changelog_path = "./CHANGELOG.md"
pr_labels = ["release"]
publish_no_verify = true

[[package]]
name = "kartoteka-api"
release = false

[[package]]
name = "kartoteka-frontend"
release = false

[changelog]
body = """
{% if version %}
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
## [Unreleased]
{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}\
{{ commit.message }}
{%- endfor %}
{% endfor %}
"""
trim = true
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^refactor", group = "Refactor" },
    { message = "^perf", group = "Performance" },
    { message = "^doc", group = "Documentation" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore", group = "Miscellaneous" },
    { message = "^ci", group = "Miscellaneous" },
]
