name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      wrangler_env: dev
      d1_database: kartoteka-dev
      pages_branch: dev
    secrets: inherit
